### PR TITLE
Replace `top` for `ps` command

### PR DESCRIPTION
**Pull request by duderamos**
The options provided to `top` are not fully compatible with MacOS version.
`ps` on the other hand, implements compatible options in both Linux and
MacOS. It is also more customizable and returns simpler output to parse.

### CODE REVIEW

**Comment by ylecuyer** [comment]
Thanks for the PR I'll give it a try :+1:

**Comment by jarthod** [comment]
That's not equivalent unfortunately, the CPU usage given by ps is the average since process startup:
https://unix.stackexchange.com/a/58541/280189. `puma-status` is using `top` to get an instantaneous CPU usage (or more precisely a 1 second average I think). Is there another alternative for that on MacOS? or other `top` options?

**Comment by duderamos** [comment]
Great comment @jarthod, thanks for that. Even though the name of the information is the same in both tools, they're different numbers. This phrase from StackExchange post summarised perfectly `It is like asking someone to calculate the speed of a car from a picture.`.

I will take some time and dive more into `proc` and `top` source code. 👍

**Comment by ylecuyer** [comment]
Thanks for the hint @jarthod 

Once again @duderamos thanks for the help, I'll close the PR meanwhile, feel free to reopen or open a new one if needed ;)

**Pull request closed without merging**
